#include <stdio.h>
#include <math.h>
void main()
{
    int q,a;
    printf("Enter the value of prime number:\n");
    scanf("%d",&q);
    printf("Enter the primitive root of a a prime number");
    scanf("%d",&a);
    int X,Y,M,N;
    printf("Enter the value of private key of A :\n");
    scanf("%d",&X);
    printf("Enter the value of private Key of B:\n");
    scanf("%d",&Y);
    N=pow(a,X);
    int C=N%q;
    printf("Thwe public Key of A is :%d\n",C);
    M=pow(a,Y);
    int D=M%q;
    printf("The public key of B is:%d\n",D);
    int k1=pow(D,X);
    int v=k1%q;
    printf("The secret key generated by A is :%d\n",v);
    int k2=pow(C,Y);
    int w=k2%q;
    printf("The secret key generated by B is :%d\n",w);
}
